### ISSUE TITLE
How to train gpt2 on mutil node and mutil gpu

### ISSUE THREAD

**Issue by 1106944911** [EleutherAI/GPTNeo#69]
what should input about gpu_ids on  mutil node and mutil gpu?below right?
node0 cmd: python3 main.py --model <your_config_name> --steps_per_checkpoint <n> --gpu_ids 0,1,2,3
node1 cmd: python3 main.py --model <your_config_name> --steps_per_checkpoint <n> --gpu_ids 0,1,2,3
node2  cmd: python3 main.py --model <your_config_name> --steps_per_checkpoint <n> --gpu_ids 0,1,2,3

**Comment by sdtblck** [comment]
Hey @1106944911 
it should be the names of your GPU devices as a list of strings separated by spaces

 i.e 
`python3 main.py --model <your_config_name> --gpu_ids device:GPU:0 device:GPU:1`

this is what @lucidrains used in testing, but your device names may differ. Let us know how training goes, we've mostly been testing on TPUs so far and have had mixed success with GPU training.

**Comment by 1106944911** [comment]
@lucidrains Hi Can you tell me how to train on multi nodes and multi gpu ?
