### ISSUE TITLE
Some minor issues with MoE

### ISSUE THREAD

**Issue by AranKomat** [EleutherAI/GPTNeo#72]
This is to let you know that there are some tiny things with MoE you may want to fix. 
https://github.com/EleutherAI/GPTNeo/blob/4bc16ff1d2e064b39f7a772a06994e44ecdcce63/models/gpt2/gpt2.py#L344-L348
- Dropout layer needs to be applied to the output of this line (m).
- You also may want to add `activation = params["activation_function"]` as an argument to `transformer_moe_layer_v1`, which would enable an activation function other than ReLU on MoE.

**Comment by lucidrains** [comment]
want to try submitting a PR?

**Comment by AranKomat** [comment]
Sid said he's going to fix it, so I think this one will be fine :) It's just two lines of fix, anyway.

**Comment by lucidrains** [comment]
if its just two lines, you should do it! it'll take 5 minutes

**Comment by sdtblck** [comment]
@lucidrains @AranKomat https://github.com/EleutherAI/GPTNeo/pull/74

**Comment by AranKomat** [comment]
That was pretty fast! I'm sorry, but I'll do PR in the next time to save your time :)

**Comment by sdtblck** [comment]
hah, not a problem.
