### ISSUE TITLE
About MLM & fine-tuning

### ISSUE THREAD

**Issue by AranKomat** [EleutherAI/GPTNeo#73]
I found the MLM option, which was probably added as an experimental option. For this, I'd like to note a few things you may find useful, specifically concerning Roberta (cuz Bert sucks lol). 

- I may be misunderstanding this, but it appears that your process of MLM doesn't include replacing a token with a random token, i.e., the second option of the figure:

![fig1](https://user-images.githubusercontent.com/29173653/99398117-f504ff80-28b1-11eb-972a-e5d8c4939c3f.png)
 
- It would be awesome if you can add the option of fine-tuning on GLUE (found it in another repo by Eleuther). Since the current MLM training doesn't add [CLS] token at the beginning, you may want to fix that.

**Comment by lucidrains** [comment]
i think the [cls] token can be added manually when preparing the dataset

for the random token replacement, I omitted it because in Electra, they removed that without it affecting learning, but I could add it back for complete-ness sake

**Comment by lucidrains** [comment]
i'll see what i can do, on Thursday

**Comment by AranKomat** [comment]
Thanks for letting me know! According to the Electra paper, it seems that this operation is still necessary for Bert/Roberta. But if we use Electra variants, then it's unncessary. Maybe we can try Electra variants only without Roberta to make it simple. In this case, the first bullet point can be ignored, and only [cls] addition is needed. 

I'll try to modify T5's implementation to enable fine-tuning on (Super-)GLUE in addition to the new Electra once released, unless you have any suggestion to save the time :)

**Comment by AranKomat** [comment]
OK I think I'll submit a PR for this [cls] thing sometime later :)
