### ISSUE TITLE
HugginFace compatibility 

### ISSUE THREAD

**Issue by WissamAntoun** [EleutherAI/GPTNeo#80]
Hey,

If a train a GPT2 model from scratch using your codebase, can it be converted to models compatible with the HuggingFace library?

Thank you

**Comment by ConnorJL** [comment]
Unfortunately, currently not. This is pretty non-trivial and HF doesn't support all of the features we have implemented. This might change in the future since obviously converting to HF would be a huge benefit, but no guarantees when/if this will arrive.

**Comment by WissamAntoun** [comment]
Thx for the reply and keep up the great work!!

**Comment by WissamAntoun** [comment]
congrats on getting the models on HuggingFace !! https://huggingface.co/EleutherAI 🚀

**Comment by anjandash** [comment]
Congratulations guys! 🎉
