### ISSUE TITLE
Fix input function to be deterministic

### ISSUE THREAD

**Issue by StellaAthena** [EleutherAI/GPTNeo#83]
Add checkpointing and make the functionality deterministic so we don't get fucked by preemption. See https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/ModelCheckpoint and https://github.com/tensorflow/mesh/blob/master/mesh_tensorflow/transformer/utils.py#L1654

**Comment by sdtblck** [comment]
https://github.com/EleutherAI/GPTNeo/pull/90
