### ISSUE TITLE
Make sure we handle short text correctly

### ISSUE THREAD

**Issue by StellaAthena** [EleutherAI/GPTNeo#86]
> As a cleaning heuristic, documents with fewer than 128 tokens were removed from the dataset. These shorter documents tended to be lower quality, as determined by text coherence. We release this dataset as the OpenWebTextCorpus

[source](https://blog.usejournal.com/opengpt-2-we-replicated-gpt-2-because-you-can-too-45e34e6d36dc)

**Comment by sdtblck** [comment]
this is already a param in create_tfrecords, it's handled correctly :)
